### PR TITLE
Add features to splice junction track

### PR DESCRIPTION
**Pull request by bw2**
Add support for more optional gffTag keys:
1. for specifying how many samples in a batch had a particular splice junction
2. for explicitly setting a feature's label, color, arc thickness, left/right arrows. This allows more flexibility to render tracks where the arcs don't necessarily represent splice junctions - for example here the arcs represent SpliceAI predictions:

image

Also, add better on-click popups for splice junctions:
image
image

TODO: need to add user docs for new options

### CODE REVIEW

**Comment by bw2** [comment]
Examples of splice junction .beds with new gffTags:

Example 1:
```
1	973176	973212	label=0.3_[1];line_width=0.8;color=#11AA11;left_shape=v;effect=acceptor_gain;summary=1_of_11_alleles_scored_above_0.2;score=0.3;allele=1-973177-T-G;	0	+
1	973177	973212	label=0.35_[1];line_width=1.1;color=#11AA11;left_shape=v;effect=acceptor_gain;summary=1_of_11_alleles_scored_above_0.2;score=0.35;allele=1-973178-CCCCA-C;	0	+
```

Example 2:
```
chr1	11671	12009	motif=GT/AG;uniquely_mapped=0;multi_mapped=1;maximum_spliced_alignment_overhang=45;annotated_junction=false;num_samples_with_this_junction=86;num_samples_total=255	0	+
chr1	14695	185174	motif=CT/AC;uniquely_mapped=1;multi_mapped=1;maximum_spliced_alignment_overhang=38;annotated_junction=false;num_samples_with_this_junction=85;num_samples_total=255	1	-
chr1	14829	14929	motif=CT/AC;uniquely_mapped=0;multi_mapped=3;maximum_spliced_alignment_overhang=39;annotated_junction=false;num_samples_with_this_junction=207;num_samples_total=255	0	-
chr1	14829	14969	motif=CT/AC;uniquely_mapped=18;multi_mapped=325;maximum_spliced_alignment_overhang=50;annotated_junction=false;num_samples_with_this_junction=169;num_samples_total=255	18	-
```

**Comment by jrobinso** [comment]
Hi Ben,  there's too much of this sort of thing, I think, and it shouldn't be necessary as of a few commits ago.   I now automatically parse name fields that look like gffTags and present the results in popup text.   Give it a try.   I'll review the rest of the PR in the next day or two.
```
   if (feature.attributes.uniquely_mapped) {
                featureData.push(
                    {name: feature.attributes.uniquely_mapped, value: 'uniquely mapped reads'})
            }
```

**Comment by bw2** [comment]
Hi Jim, I just removed some. For others, especially with numeric values, I thought it looked better with the number on the left in bold, so I swapped the "key" and "value" field.  To keep featureTrack clean, would it help if I factored out splice junction track as a separate subclass of featureTrack?

**Comment by jrobinso** [comment]
Well,  coincidentally I just converted all the prototype chain syntax to classes for tracks.   That's in a branch, "classes",  so we're going to need to merge your PR and that one together.  But subclassing is a blunt instrument and maybe too heavy for this.   Another alternative is to just plug-in (replace) the popup data function for this track type.   Then there is 1 if statement,  if type is splice junction this.popupData = myFunction, or something like that.     However, all other tracks users will encounter are using a different convention for popup text,  they are going to understand the text either way but I think it should look uniform across track types as much as possible.

**Comment by bw2** [comment]
That sounds great. Let me know when/how best to merge this with "classes".

**Comment by jrobinso** [comment]
@bw2 I just merged the "classes" branch,  so for you do a reverse merge and resolve the conflicts,  or start a new branch and just manually re-apply your changes.   That might be the easiest path.    Sorry, this is unfortunate timing, but the "class" syntax should be easier to work with than the old prototype chain approach.     

Is there any functionality here other than re-formatting popup text?  If so let's do that first,  then deal with popup text formatting.   I'm not crazy about the idea of special layout for just 1 type of track,  but if some specialization is needed plugging in a "popupData" function might be better than subclassing.

**Comment by bw2** [comment]
Thanks, I'll start merging next week.

**Comment by bw2** [comment]
Hi Jim, I think I'm done merging with latest master.

**Comment by bw2** [comment]
Also, what's a reasonable way to replace the popupData function for spliceJunction tracks during or after track creation?
I'm having trouble figuring this out.

**Comment by jrobinso** [comment]
This will be a problem in multi-locus view

```
            if (this.config.type == 'spliceJunctions') {
                const vp = this.browser.trackViews[0].viewports[0]
```

The current viewport is a property of the "options" argument passed to draw, so this should work unless I'm missing something

```
const vp = options.viewport
```

To test multi-locus view just enter 2 loci in the address bar separated by a space, e.g.  ```egfr myc```.

I'll think about replacing popup data,  not sure,  subclassing FeatureTrack seems to heavy for this purpose.   Of course you could just replace the popupData function in the track factory, that seems a bit hacky though better than subclassing.

**Comment by bw2** [comment]
Wow, I didn't know about multi-locus view! That's a cool feature.

options.viewport works, and I'm able to monkey-patch the popupData function with 
```
igv.createBrowser(this.container, igvBrowserOptions).then((browser) => {
      browser.trackViews.forEach((trackView) => {
        if (trackView.track.type === 'spliceJunctions') {
          trackView.track.popupData = popupData
        }
      })
})
```

**Pull request merged**
