### PR TITLE
igvjs now bundles jquery-ui

### PR DESCRIPTION
**Pull request by turner**
igvjs now bundles jquery-ui

### CODE REVIEW

**Comment by paul-shannon** [comment]
@jrobinso, @turner  - building  a local copy of igv.js/dist/igv.js using your Gruntfile.js, after a fresh pull this morning, I once again encounter this error:
 
    this.$popover.draggable is not a function
    at igv.Popover.initializationHelper (index.js?v=20171106115146:89151)
    at new igv.Popover (index.js?v=20171106115146:89125)
    at Object.igv.createBrowser (index.js?v=20171106115146:80626)
    at child.initializeIGV (index.js?v=20171106115146:384)
    at index.js?v=20171106115146:393

dist/igv.js has (as we expect) a copy of jquery-ui.js contained within it.  
Maybe this "not a function" is somehow related to changes involved in bundling jquery-ui?

We exchanged some email on this, and the commit "Disable Popover dragging"  was merged  on October 18th:

    https://github.com/igvteam/igv.js/pull/442

As always, I may be missing something obvious.  Any advice for me?

 - Paul

For what it's worth, if I pause execution before the error ````this.popover````  here is what I see:

image

and, for more detail:
image

**Comment by jrobinso** [comment]
Hi Paul,
Apologies, we made a mistake with our grunt packaging.   Could you pull and try again?

**Comment by jrobinso** [comment]
And a follow-on,  are you using NPM?

**Comment by paul-shannon** [comment]
Hi Jim,

Yes, I am using npm.   

I don’t know if these details are relevant, but my procedure is:

pull the latest from your igv.js repo, run grunt then copy the resulting igv.js, igv.css and images to a my own dedicated igv.js.npm repo, where npm finds it via this dependency in the package.json of my app

      "igv_js_npm": "github:paul-shannon/igv.js.npm”,

and these lines in the app itself

var igv = require('igv.js.npm')
require('igv.js.npm/igv.css')

**Comment by jrobinso** [comment]
OK, thanks for the details.    Did you pull fresh and try again?  We were
inadvertently registering our embedded jquery-ui  with NPM,  that has been
removed,  so all the files included in igv.js should be local to the igv
function object.

Let me know if the problem persists after a fresh pull.

**Comment by jrobinso** [comment]
Actually hold on -- I've been able to reproduce the problem here.   Will update when there is a fix.

**Comment by jrobinso** [comment]
OK, good to go now.

**Comment by paul-shannon** [comment]
It works!  Many thanks.

If the igvteam ever decides to offer your own official npm-via-github version of igv.js, please let me know.   It is refreshingly easy, as you can see at this working (if unpolished) example

   https://github.com/paul-shannon/igv.js.npm

To sweeten the deal ;} I could add a tiny app demonstrating how to use this igv.js node module.  This would include the sometimes confusing directory structure,  package.json, webpack.config.js and javascript needed to actually invoke igv.js in the standard node module style.

 - Paul

**Comment by jrobinso** [comment]
Hi Paul,  that would be awesome we would love to do that.   I have zero
experience with NPM,  that's why its not done yet,  but if you say its easy
I'll put it on my to-do list.

Could you write out instructions for making the module for a total nube?

Thanks

Jim

**Comment by jrobinso** [comment]
BTW, maybe you should open a new git issue for this  "Igv.js as NPM
module",  and we'll continue the conversation there.

**Pull request merged**
