### PR TITLE
Repair Track AutoHeight.

### PR DESCRIPTION
**Pull request by turner**
Repair Track AutoHeight.

### CODE REVIEW

**Comment by jimhavrilla** [comment]
is this in reference to #524?  Thanks!

**Comment by jrobinso** [comment]
This should be fixed now.  Pull and give it a try.

**Comment by jimhavrilla** [comment]
image

So now the height DOES autoexpand when adding autoHeight: true but the scroll bar seems to not be there anymore.  Must be a bug.  Because there are more transcripts in the Squished view and I cannot scroll.

image

**Comment by jimhavrilla** [comment]
In reference to #524

**Pull request merged**
