### PR TITLE
Add dev container

### PR DESCRIPTION
**Pull request by PeterKnealeCMRI**
This PR adds a dev container per discussion.
Opening the repository in VS Code when this file is present will create a dokcer image, install the necessary dependencies then all development in the pre-configured environment.
https://github.com/igvteam/igv.js/issues/1881

### CODE REVIEW

**Comment by jrobinso** [comment]
It looks simple enough, but there is a maintenance issue here as no one on this team use VS.

**Comment by PeterKnealeCMRI** [comment]
VS Code is just one editor supporting this new(ish) standard. 
IntelliJ IDEA and others support it to if you happen to use that. The list  is here: https://containers.dev/supporting

Github itself supports it, once this file is present in the repo, you can just click on code-spaces and provision a web based version of vscode and have the same environment installed.. I've found for a few bits of bioinformatics pieces of work with large  fasta files etc, the cloud based editors are actually much quicker to work with because of their proximity to resources like s3 etc.

image

I dont think there is a large maintenance burden, it just makes pulling down a repo and working on it that bit simpler without worrying about what versions of node/npm/packages are installed.

**Comment by jrobinso** [comment]
It is a burden for us.  If we commit to having this in our repository we commit to testing and maintaining it.     I don't understand the comment on package versions, those are all nailed down in package.json.   We should add a note on required node version to the readme, to be honest I don't know what that is.   Probably anything later than 12.

**Comment by PeterKnealeCMRI** [comment]
Thats okay, I appreciate you have limited time. 
Thanks for your efforts on the library - its very useful.

**Pull request closed without merging**
