### PR TITLE
Instead of erroring, provide slice of loaded data

### PR DESCRIPTION
**Pull request by romanzenka**
I am getting ArrayBuffer from the response which has a convenient .slice method that is useful for this sort of situation.

Fixing issue #1049

### CODE REVIEW

**Comment by jrobinso** [comment]
This is nice, but how do we handle the not-uncommon case of someone trying to use a simple server with no range support to serve large files?    We want to discourage that.  Perhaps we could add a check on the range requested, if its > some threshold we error.   Is that reasonable?

**Comment by romanzenka** [comment]
I think that erroring out because user did something that is sub-optimal is pretty harsh. 

But then I do not deal with the users reporting low performance...

What if we limit the file to ... I do not know, 100 kilobytes? If it is more than that, you get an error, if less than that, we let it slide?

**Comment by romanzenka** [comment]
I added the check for the amount of data loaded being small <100kb

**Comment by jrobinso** [comment]
I was thinking more like 100 mb, or at least 1 mb.    Thanks for the PR this is an improvement.

**Comment by jrobinso** [comment]
OTOH if the response data is already in memory and the browser hasn't frozen I guess its not a problem.    I still don't understand why you are seeing this, we have unit tests that request a single byte.  I have seen the issue in some organizations that use proxies that strip the range header from the outgoing request.

**Comment by jrobinso** [comment]
@romanzenka So I pushed a change to warn user if file is > 100kb, and never error out.   If performance tanks maybe they'll remember the warning and investigate further.

**Comment by romanzenka** [comment]
@jrobinso Thank you! I am still investigating to understand exactly why this is happening. I have seen it in two instances - once with a simple python server, and once with built-in IntelliJ server.

**Comment by jrobinso** [comment]
I know the built-in intellij server does not support the range header.
 Flask can support it,  I think it does by default know,  I don't know
about other python servers.

**Pull request merged**
