### PR TITLE
#303 concat css, concat and minify css, and copy img to dist folder when building with grunt

### PR DESCRIPTION
**Pull request by david-ma**
See issue #303

### CODE REVIEW

**Comment by jrobinso** [comment]
Hi,  the igv-gtex.css and opentip.css files are not used, and shouldn't be included.  Where did you see references to them?   Also, we had issues after minimizing the css with grunt in the past,  that's why we don't do it.   What is the advantage?  Its a tiny file already.   Minimizing it is o.k. as long as the unminimized version is also copied.

**Comment by david-ma** [comment]
OH! Ok, this commit is unnecessary then.

1. I wasn't sure which .css files were needed, so I was including all of them just to be safe.
2. With multiple .css files, concatenating them would be a good thing to do.
3. After concatenation, adding the minification step is trivial.

---

I still think it would be good to copy the igv.css and img/* stuff to the dist folder on running grunt, so it is clear which files should be distributed.

**Comment by jrobinso** [comment]
Yes, agreed.  You can submit a PR for just that, or open a git issue and we
will do it.  I'm on IGV desktop for the next few weeks.

**Comment by david-ma** [comment]
Ok cool, I'll make a new PR tomorrow. This one can be closed.

**Pull request closed without merging**
