### PR TITLE
Hor lines

### PR DESCRIPTION
**Pull request by docwarren**
See #1023

### CODE REVIEW

**Comment by jrobinso** [comment]
@docwarren @blajoie Is this ready for review yet, or are you still pushing changes?

**Comment by docwarren** [comment]
@jrobinso yes, you can review. Thanks. 
Andrew

**Comment by jrobinso** [comment]
@docwarren the wig drawing implementation was changed, and I can't parse and visualize the results in my head.  What cases were tested?  Specifically were wig tracks with all negative values, as well as a mix of positive and negative values tested?

**Comment by docwarren** [comment]
To be honest - no - just tested on positive values. Lemme go ahead and do that. Will get back to you.

**Comment by docwarren** [comment]
Screen Shot 2019-12-11 at 2 49 40 PM
Using files from test/data/wig

**Comment by docwarren** [comment]
Added an all negative bedgraph and it looks good.

**Comment by docwarren** [comment]
Heres what the dotted lines look like.
Screen Shot 2019-12-11 at 2 58 35 PM

I need to test negative values in a point plot still

**Comment by docwarren** [comment]
Screen Shot 2019-12-12 at 10 44 50 PM

**Comment by docwarren** [comment]
Screen Shot 2019-12-12 at 11 00 47 PM
Plus guidelines

**Comment by docwarren** [comment]
@jrobinso 
I tried to simplify the maths quite a bit. I think its easier to understand now.
Tested using new example html and test data that I added to the examples datadir.
Hope this all looks OK to you.
Best Andrew

**Pull request closed without merging**
